" Time to take this bad boy back to the basics
"
" Author: Mark Bluemer
" Contributions taken from:
" * Ben Orenstein
" * Amir Salihefendic
" * Mathias Bynens
" * Alexey Shmalko 
"
" Last change: May 12 2016


" Use Vim settings rather than Vi settings
" This must stay first
set nocompatible

" Causes vim to source from any directory you run vim from
" if there's a vimrc available
" Setting secure restricts commands in non-default vimrc files
set exrc
set secure

" Change runtime path for Pathogen
execute pathogen#infect()

" Set the mapleader
let mapleader = ","

" Fix the backspace key
set backspace=indent,eol,start

" Switch syntax highlighting on
syntax enable
set background=dark
colorscheme solarized

" Set highlight for line that cursor is on
set cursorline

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Set line numbering
set number

" Show invisible characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

" Use spaces instead of tabs
set expandtab

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

" wrap lines
set wrap

" Remove that annoying beeping and flashing
set visualbell
set t_vb=

" For sake of practice I'm going to go ahead and remove the arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Here are some mappings for vimwiki
noremap <leader>gl :VimwikiDiaryGenerateLinks
noremap <leader>da :r! date +"\%Y-\%m-\%d \%H:\%M:\%S"<ESC>0=j  
