" Time to take this bad boy back to the basics
"
" Author: Mark Bluemer
" Contributions taken from:
" * Ben Orenstein
"
" Last change: May 2 2016


" Use Vim settings rather than Vi settings
" This must stay first
set nocompatible

" Change runtime path for Pathogen
execute pathogen#infect()

" Set the mapleader
let mapleader = ","

" Fix the backspace key
set backspace=indent,eol,start

" Switch syntax highlighting on
syntax on

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Set line numbering
set number

" For sake of practice I'm going to go ahead and remove the arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Here are some mappings for vimwiki
noremap <leader>gl :VimwikiDiaryGenerateLinks
