" Time to take this bad boy back to the basics
"
" Author: Mark Bluemer
" Contributions borrowed from:
" * Ben Orenstein
" * Amir Salihefendic
" * Mathias Bynens
" * Alexey Shmalko 
" * Feferico Ramirez
"
" Last change: July 23 2016


" Use Vim settings rather than Vi settings
" This must stay first
set nocompatible

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" Make sure encoding is always utf 8
set encoding=utf-8
set fileencoding=utf-8

" Causes vim to source from any directory you run vim from
" if there's a vimrc available
" Setting secure restricts commands in non-default vimrc files
set exrc
set secure

" Change runtime path for Pathogen
execute pathogen#infect()

" Fix the backspace key
set backspace=indent,eol,start

" Switch syntax highlighting on
syntax enable
set background=dark
colorscheme solarized

" Set highlight for line that cursor is on
set cursorline

" Set line numbering
set number

" Show invisible characters
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_
set list

" Use spaces instead of tabs
set expandtab

" 1 tab == 4 spaces
set shiftwidth=4
set tabstop=4

" wrap lines
set wrap

" Remove that annoying beeping and flashing
set visualbell
set t_vb=

" Set the mapleader
let mapleader = ","

" For sake of practice I'm going to go ahead and remove the arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Here are some mappings for vimwiki
noremap <leader>gl :VimwikiDiaryGenerateLinks
noremap <leader>da :r! date +"\%Y-\%m-\%d \%H:\%M:\%S"<ESC>0=j  

" -------------- Time to Make the Change to Vundle ---------------- "
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Globally useful plugins
Plugin 'altercation/vim-colors-solarized'
Plugin 'vimwiki/vimwiki'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/L9'
Plugin 'vim-scripts/FuzzyFinder'
Plugin 'tpope/vim-surround'
Plugin 'Valloric/YouCompleteMe'

" Plugins for Web Development
Plugin 'Shutnik/jshint2.vim'
Plugin 'skammer/vim-css-color'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'pangloss/vim-javascript'


" All plugins must be added before this line, required
call vundle#end()

" run JSHint when a file with a .js extension is saved
autocmd BufWritePost *.js silent :JSHint
